init.d/functions: Make usage msgs more clear
fedora-sysv/initscripts pull request #347
Opened 2020-10-20 10:30 UTC by jamacku

2020-10-22 09:58 UTC, jamacku commented
CI Output:
```
E: Unable to locate package csbuild

The command "sudo apt-get install -y --force-yes csbuild" failed and exited with 100 during .
```

2020-11-05 13:08 UTC, lnykryn requested changes

2020-11-05 13:08 UTC, lnykryn commented on etc/rc.d/init.d/functions
> +            echo $"Usage: status [-p {pidfile} [-b {binary}]] [-l lockfile] {program}"
Looking at the code above, this does not seem correct. Currently we parse it in the -p -l- b order

2020-11-05 13:55 UTC, jamacku commented on etc/rc.d/init.d/functions
> +            echo $"Usage: status [-p {pidfile} [-b {binary}]] [-l lockfile] {program}"
Yes, you are right, thank you.

2020-11-05 14:02 UTC, jamacku commented on etc/rc.d/init.d/functions
> +            echo $"Usage: status [-p {pidfile} [-b {binary}]] [-l lockfile] {program}"
Actually, I wanted to somehow express this relation:
``"-b option can be used only with -p"``

2020-11-05 14:23 UTC, lnykryn approved these changes

2020-11-06 07:02 UTC, merged