ci: Migrate from Travis to GH Actions
fedora-sysv/initscripts pull request #372
Opened 2021-03-10 13:09 UTC by jamacku

There are two workflows, integration_test and shellcheck_test.
Those are similar to original travis jobs.

2021-03-10 13:40 UTC, mrc0mmand requested changes

2021-03-10 13:40 UTC, mrc0mmand commented on .github/workflows/check-shell.sh
> +PWD=".github/workflows"
This is a bit risky, since `$PWD` gets overwritten with every `cd`, e.g.:

```bash
#!/bin/bash -x

echo "$PWD"
PWD="test"
echo "$PWD"
cd /tmp
echo "$PWD"
```

```
$ ./test.sh
+ echo /home/mrc0mmand/tmp/bash
/home/mrc0mmand/tmp/bash
+ PWD=test
+ echo test
test
+ cd /tmp
+ echo /tmp
/tmp
```

It may work, in this case, since there are no `cd`s involved, but it may cause unexpected issues in the future.

Also, you can *detect* the script's working directory by using something like:

```bash
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
```

so you don't have to figure out the path manually each time you shuffle the scripts around.

2021-03-10 13:40 UTC, mrc0mmand commented on .github/workflows/check-shell.sh
> +file_to_array "./${PWD}/script-list.txt" "list_of_scripts" 1
With the proposed changes above this can be then changed to:

```bash
file_to_array "$SCRIPT_DIR/script-list.txt" "list_of_scripts" 1
```

2021-03-10 13:40 UTC, mrc0mmand commented on .github/workflows/check-shell.sh
> +file_to_array "./${PWD}/exception-list.txt" "list_of_exceptions" 1
ditto

2021-03-11 06:41 UTC, jamacku commented on .github/workflows/check-shell.sh
> +PWD=".github/workflows"
That is a good point. Thank you.

2021-03-11 10:31 UTC, jamacku commented
Test of CI: https://github.com/jamacku/initscripts/pull/34/checks

2021-03-11 12:25 UTC, merged