retry arping one more time in ifup-eth when sendto failed
fedora-sysv/initscripts pull request #490
Opened 2024-09-25 08:06 UTC by xanoxes

retry arping one more time in ifup-eth when sendto failed

2024-10-11 02:31 UTC, xanoxes commented
You're right, its ugly. So i refactor it with ARPING_TRIES. Please review this PR again.

2024-10-11 11:13 UTC, lnykryn requested changes

2024-10-11 11:13 UTC, lnykryn commented on network-scripts/ifup-eth
> +                    while [ $tries -le $ARPING_TRIES ]
We tend to keep "while ...; do" on one line. Also, it is a good practice to always put variables in the statement into double quotes

2024-10-11 11:13 UTC, lnykryn commented on network-scripts/ifup-eth
> +                        if [ $? = 1 ]; then
This will cause that "Error, some other host ".... message to be needlessly printed several times. It would be better to structure the code something like this:
while .. do
    arping
    ret=$?
done
if [ ret =1 ] ....

2024-10-11 11:13 UTC, lnykryn commented on network-scripts/ifup-eth
> +                            if [ $tries -gt $ARPING_TRIES ]
Same as above, this should be checked after the cycle. And again missing double quotes

2024-10-11 11:13 UTC, lnykryn commented on network-scripts/ifup-eth
> +                                net_log "arping failed after $tries tries"
Missing $ so the string could be translated  ($"string")

2024-10-11 11:14 UTC, lnykryn commented
And please squash your commits.

2024-10-21 07:33 UTC, xanoxes commented
@lnykryn

2024-11-11 01:32 UTC, xanoxes commented
@lnykryn

2024-11-11 11:17 UTC, lnykryn commented
> This will cause that "Error, some other host ".... message to be needlessly printed several times. It would be better to structure the code something like this: while .. do arping ret=$? done if [ ret =1 ] ....

I don't think this was addressed.

2024-11-13 08:54 UTC, xanoxes commented
> > This will cause that "Error, some other host ".... message to be needlessly printed several times. It would be better to structure the code something like this: while .. do arping ret=$? done if [ ret =1 ] ....
> 
> I don't think this was addressed.

We now only print "Error, some other host ".... once there really is an $ARPINGMAC in output of ARPING. In this case we exit the loop directly so there would not be a repeated Error msg print.

2024-11-15 14:15 UTC, lnykryn commented
> > > This will cause that "Error, some other host ".... message to be needlessly printed several times. It would be better to structure the code something like this: while .. do arping ret=$? done if [ ret =1 ] ....
> > 
> > 
> > I don't think this was addressed.
> 
> We now only print "Error, some other host ".... once there really is an $ARPINGMAC in output of ARPING. In this case we exit the loop directly so there would not be a repeated Error msg print.

Ah, I missed the break, sorry.

2024-11-15 14:17 UTC, lnykryn commented on network-scripts/ifup-eth
> +                        else
Can you flip this a bit? I think this would be nicer:
ARPING=$(/sbin/arping -c 2 -w ${ARPING_WAIT:-3} -D -I ${REALDEVICE} ${ipaddr[$idx]})
[ $? = 0 ] && break
 ARPINGMAC=$(echo $ARPING |  sed -ne 's/.*\[\(.*\)\].*/\1/p')
....

2024-11-19 11:54 UTC, lnykryn requested changes

2024-11-19 11:54 UTC, lnykryn commented on network-scripts/ifup-eth
> +                            break
Shouldn't it be here "exit 1" instead of "break"? If we find a duplicate address on the first iteration loop, then the if [ "${tries}" -gt "${ARPING_TRIES}" ]; check below will be false, and we will continue with the rest of the code.

2024-11-19 13:22 UTC, xanoxes commented
@lnykryn All done, plz check.

2024-11-19 13:30 UTC, lnykryn commented
I still think that there should be exit 1 instead of break on line 302 in your code

2024-11-19 15:32 UTC, xanoxes commented
> I still think that there should be exit 1 instead of break on line 302 in your code

YES, its wrong to use break, fixed.

2024-12-09 01:40 UTC, xanoxes commented
@lnykryn ALL fixed, plz check

2024-12-09 15:39 UTC, jamacku requested changes

2024-12-09 15:39 UTC, jamacku commented on network-scripts/ifup-eth
> +                        tries=$((tries+1))
It will be handled in the head of the  `for` loop.

```suggestion
```

2024-12-09 15:39 UTC, jamacku commented on network-scripts/ifup-eth
> +                    if [ "${tries}" -gt "${ARPING_TRIES}" ]; then
When using `for` loop, you need to update this condition

```suggestion
                    if [ "${tries}" -eq "${ARPING_TRIES}" ]  && [ "${arping_exit_code}" -ne 0 ]; then
```

2024-12-09 15:39 UTC, jamacku commented on network-scripts/ifup-eth
> +                        [ $? = 0 ] && break
```suggestion
                        [ "${arping_exit_code:=$?}" -eq 0 ] && break
```

2024-12-23 15:37 UTC, xanoxes reviewed
LGTM

2024-12-27 01:15 UTC, xanoxes commented
@lnykryn All Fixed, plz check if any other issues.

2025-01-20 01:23 UTC, xanoxes commented
@lnykryn plz check

2025-01-20 15:42 UTC, lnykryn approved these changes

2025-01-21 07:50 UTC, merged